name = "SumOfThreeSq"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SumOfThreeSq"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "no-modules/1d663ae67d8088111bb37c3c526fe2d43e4df01c"

[[lean_lib]]
name = "SumOfThreeSq"

